### ISSUE TITLE
Collector Mendix info about screensize/form/roles etc

### ISSUE THREAD

**Issue by pimvdnoll** [richardedens/jiraissuecollectorwidget#1]
Is it possible to collect also the data the default Mendix feedback widget collects?

Like:
Active userroles	
Account logged in
Active form
Screen size
Browser
Application location

Than is it a perfect replacement 👍

**Comment by richardedens** [comment]
Hi Pim,

When you configure the issue collector you are able to add fields that people can enter or you can send into the issue. It is also possible to collect some of your wishes with the standard JIRA issue collector settings.

To awnser your question fully, I am working on a JIRA API connector. Build with the Mendix Connector Kit. That will allow at first the creation of issues with the options you want. There will then also be a JIRA API widget that can collect the required information as requested.

So... this was step one. The JIRA API connector is step to.

Kind regards,


Richard

**Comment by pimvdnoll** [comment]
cool, looking forward.
